In [15]:
import pandas as pd

In [16]:
df = pd.read_csv("gk_qna_dataset.csv")
df

                                              question   answer
0                     What is the capital of "France"?    Paris
1                    What is the capital of "Germany"?   Berlin
2                      What is the capital of "Italy"?     Rome
3                      What is the capital of "Spain"?   Madrid
4                      What is the capital of "Japan"?    Tokyo
..                                                 ...      ...
166          Can you tell me, "Which bird cannot fly"?  Ostrich
167  I was wondering, "What is 'H2O' commonly called"?    Water
168  I was wondering, "Which planet is known as the...     Mars
169  Can you tell me, "What is the main religion in...    Islam
170  Quick question: "Which animal is known for loy...      Dog

[171 rows x 2 columns]

In [17]:
df['question']

0                       What is the capital of "France"?
1                      What is the capital of "Germany"?
2                        What is the capital of "Italy"?
3                        What is the capital of "Spain"?
4                        What is the capital of "Japan"?
                             ...
166            Can you tell me, "Which bird cannot fly"?
167    I was wondering, "What is 'H2O' commonly called"?
168    I was wondering, "Which planet is known as the...
169    Can you tell me, "What is the main religion in...
170    Quick question: "Which animal is known for loy...
Name: question, Length: 171, dtype: object

In [18]:
df['question'][0]

'What is the capital of "France"?'

# Tokenize

In [19]:
import re
def tokenize(text):
  # lowercase
  text = text.lower()
  #remove quotes
  text = re.sub( r"[\"']","",text )
  #remove punctuations
  text = re.sub(r"^a-z0-9\s"," ",text)
  #tokenize plit into words
  tokens = text.split()

  return tokens

In [20]:
print(tokenize(df['question'][0]))

['what', 'is', 'the', 'capital', 'of', 'france?']

In [21]:
vocab = {'<UNK>':0}

In [33]:
def build_vocab(row):
  tokenized_question = tokenize(row['question'])
  tokenized_answer = tokenize(row['answer'])

  marged_tokens = tokenized_question + tokenized_answer

  for token in marged_tokens:
    if token not in vocab:
      vocab[token] = len(vocab)

In [34]:
df.apply(build_vocab,axis=1)

0      None
1      None
2      None
3      None
4      None
       ...
166    None
167    None
168    None
169    None
170    None
Length: 171, dtype: object

In [35]:
vocab

{'<UNK>': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france?': 6,
 'paris': 7,
 'germany?': 8,
 'berlin': 9,
 'italy?': 10,
 'rome': 11,
 'spain?': 12,
 'madrid': 13,
 'japan?': 14,
 'tokyo': 15,
 'canada?': 16,
 'ottawa': 17,
 'brazil?': 18,
 'brasilia': 19,
 'australia?': 20,
 'canberra': 21,
 'india?': 22,
 'new': 23,
 'delhi': 24,
 'china?': 25,
 'beijing': 26,
 'russia?': 27,
 'moscow': 28,
 'united': 29,
 'states?': 30,
 'washington': 31,
 'dc': 32,
 'mexico?': 33,
 'mexico': 34,
 'city': 35,
 'egypt?': 36,
 'cairo': 37,
 'turkey?': 38,
 'ankara': 39,
 'argentina?': 40,
 'buenos': 41,
 'aires': 42,
 'south': 43,
 'korea?': 44,
 'seoul': 45,
 'indonesia?': 46,
 'jakarta': 47,
 'pakistan?': 48,
 'islamabad': 49,
 'bangladesh?': 50,
 'dhaka': 51,
 'nepal?': 52,
 'kathmandu': 53,
 'sri': 54,
 'lanka?': 55,
 'colombo': 56,
 'thailand?': 57,
 'bangkok': 58,
 'malaysia?': 59,
 'kuala': 60,
 'lumpur': 61,
 'vietnam?': 62,
 'hanoi': 63,
 'uae?': 64,
 'abu': 65,
 'dhabi': 66,
 'iran?': 67,
 'tehran': 68,
 'iraq?': 69,
 'baghdad': 70,
 'saudi': 71,
 'arabia?': 72,
 'riyadh': 73,
 'nigeria?': 74,
 'abuja': 75,
 'kenya?': 76,
 'nairobi': 77,
 'chile?': 78,
 'santiago': 79,
 'who': 80,
 'discovered': 81,
 'gravity?': 82,
 'isaac': 83,
 'newton': 84,
 'invented': 85,
 'telephone?': 86,
 'alexander': 87,
 'graham': 88,
 'bell': 89,
 'h2o': 90,
 'commonly': 91,
 'called?': 92,
 'water': 93,
 'which': 94,
 'gas': 95,
 'do': 96,
 'plants': 97,
 'absorb?': 98,
 'carbon': 99,
 'dioxide': 100,
 'planet': 101,
 'known': 102,
 'as': 103,
 'red': 104,
 'planet?': 105,
 'mars': 106,
 'painted': 107,
 'mona': 108,
 'lisa?': 109,
 'leonardo': 110,
 'da': 111,
 'vinci': 112,
 'largest': 113,
 'ocean?': 114,
 'pacific': 115,
 'ocean': 116,
 'developed': 117,
 'theory': 118,
 'relativity?': 119,
 'albert': 120,
 'einstein': 121,
 'ai': 122,
 'short': 123,
 'for?': 124,
 'artificial': 125,
 'intelligence': 126,
 'ml': 127,
 'machine': 128,
 'learning': 129,
 'nlp': 130,
 'natural': 131,
 'language': 132,
 'processing': 133,
 'does': 134,
 'cpu': 135,
 'stand': 136,
 'central': 137,
 'unit': 138,
 'ram?': 139,
 'computer': 140,
 'memory': 141,
 'gpu': 142,
 'graphics': 143,
 'a': 144,
 'url?': 145,
 'web': 146,
 'address': 147,
 'http': 148,
 'hypertext': 149,
 'transfer': 150,
 'protocol': 151,
 'json': 152,
 'used': 153,
 'data': 154,
 'exchange': 155,
 'sql?': 156,
 'database': 157,
 'query': 158,
 'api': 159,
 'mean?': 160,
 'application': 161,
 'programming': 162,
 'interface': 163,
 'light': 164,
 'bulb?': 165,
 'thomas': 166,
 'edison': 167,
 'airplane?': 168,
 'wright': 169,
 'brothers': 170,
 'penicillin?': 171,
 'fleming': 172,
 'wrote': 173,
 'hamlet?': 174,
 'william': 175,
 'shakespeare': 176,
 'harry': 177,
 'potter?': 178,
 'j': 179,
 'k': 180,
 'rowling': 181,
 'country': 182,
 'land': 183,
 'rising': 184,
 'sun?': 185,
 'japan': 186,
 'animal': 187,
 'called': 188,
 'king': 189,
 'jungle?': 190,
 'lion': 191,
 'on': 192,
 'earth?': 193,
 'blue': 194,
 'whale': 195,
 'bird': 196,
 'cannot': 197,
 'fly?': 198,
 'ostrich': 199,
 'for': 200,
 'loyalty?': 201,
 'dog': 202,
 'fruit': 203,
 'typically': 204,
 'red?': 205,
 'apple': 206,
 'yellow?': 207,
 'banana': 208,
 'organ': 209,
 'pumps': 210,
 'blood?': 211,
 'heart': 212,
 'humans': 213,
 'breathe?': 214,
 'oxygen': 215,
 'metal': 216,
 'liquid': 217,
 'at': 218,
 'room': 219,
 'temperature?': 220,
 'mercury': 221,
 'instrument': 222,
 'measures': 223,
 'thermometer': 224,
 'pressure?': 225,
 'barometer': 226,
 'main': 227,
 'portuguese': 228,
 'spanish': 229,
 'religion': 230,
 'in': 231,
 'islam': 232,
 'national': 233,
 'royal': 234,
 'bengal': 235,
 'tiger': 236,
 'quick': 237,
 'question:': 238,
 'penicillin': 239,
 '—': 240,
 'you': 241,
 'know?': 242,
 'know,': 243,
 'i': 244,
 'was': 245,
 'wondering,': 246,
 'hey,': 247,
 'about': 248,
 'this:': 249,
 'telephone': 250,
 'pressure': 251,
 'can': 252,
 'tell': 253,
 'me,': 254,
 'earth': 255,
 'blood': 256,
 'lisa': 257,
 'bangladesh': 258,
 'fly': 259,
 'bulb': 260,
 'sun': 261}

In [45]:
def text_to_indices(text,vocab):
  indexed_text = []



  for token in tokenize(text):
    # print(token)
    if token in vocab:
      indexed_text.append(vocab[token])
    else:
      indexed_text.append(vocab['<UNK>'])

  return indexed_text

In [46]:
text_to_indices("What is Phitron",vocab)

[1, 2, 0]

# Dataset and Dataloader

In [48]:
import torch
from torch.utils.data import Dataset,DataLoader

In [49]:
index = 0
text_to_indices(df.iloc[index]['question'],vocab)

[1, 2, 3, 4, 5, 6]

In [51]:
class QADataset(Dataset):
  def __init__(self,df,vocab):
    self.df = df
    self.vocab = vocab

  def __len__(self):
    return self.df.shape[0]

  def __getitem__(self,index):
    numerical_question = text_to_indices(self.df.iloc[index]['question'],self.vocab)
    numerical_answer = text_to_indices(self.df.iloc[index]['answer'],self.vocab)

    return torch.tensor(numerical_question),torch.tensor(numerical_answer)

In [52]:
dataset = QADataset(df,vocab)

In [54]:
dataset[1]

(tensor([1, 2, 3, 4, 5, 8]), tensor([9]))

In [55]:
dataloader = DataLoader(dataset,batch_size=1,shuffle=True)

In [56]:
for question,answer in dataloader:
  print(question,answer[0])

tensor([[ 94, 101,   2, 102, 103,   3, 104, 105]]) tensor([106])
tensor([[ 96, 241, 243,  94, 216,   2, 217, 218, 219, 220]]) tensor([221])
tensor([[244, 245, 246,   1,   2, 144, 145]]) tensor([146, 147])
tensor([[237, 238,  94, 209, 210, 211]]) tensor([212])
tensor([[ 94, 203,   2, 207]]) tensor([208])
tensor([[244, 245, 246,  80,  85,   3,  86]]) tensor([87, 88, 89])
tensor([[ 1,  2,  3,  4,  5, 48]]) tensor([49])
tensor([[ 96, 241, 243,   1,   2, 127, 123, 124]]) tensor([128, 129])
tensor([[ 96, 241, 243,   1,   2,  90,  91,  92]]) tensor([93])
tensor([[ 94, 187,   2, 188,   3, 189,   5, 190]]) tensor([191])
tensor([[237, 238,  80,  81, 171]]) tensor([ 87, 172])
tensor([[ 1,  2,  3,  4,  5, 71, 72]]) tensor([73])
tensor([[237, 238,  80,  85,   3,  86]]) tensor([87, 88, 89])
tensor([[252, 241, 253, 254,   1,   2,   3, 227, 230, 231,  71,  72]]) tensor([232])
tensor([[237, 238,  94, 216,   2, 217, 218, 219, 220]]) tensor([221])
tensor([[ 1,  2,  3,  4,  5, 57]]) tensor([58])
tensor([[  1,   2, 139]]) tensor([140, 141])
tensor([[ 94, 187,   2,   3, 113, 192, 255, 240,  96, 241, 242]]) tensor([194, 195])
tensor([[ 1,  2,  3,  4,  5, 64]]) tensor([65, 66])
tensor([[ 94, 222, 223, 220]]) tensor([224])
tensor([[ 94, 196, 197, 198]]) tensor([199])
tensor([[ 1,  2,  3,  4,  5, 10]]) tensor([11])
tensor([[237, 238,  94, 187,   2, 102, 200, 201]]) tensor([202])
tensor([[80, 85,  3, 86]]) tensor([87, 88, 89])
tensor([[  1,   2,   3, 233, 187,   5,  50]]) tensor([234, 235, 236])
tensor([[244, 245, 246,  94, 187,   2, 102, 200, 201]]) tensor([202])
tensor([[ 1,  2,  3,  4,  5, 38]]) tensor([39])
tensor([[ 1,  2,  3,  4,  5, 29, 30]]) tensor([31, 32])
tensor([[247,   1, 248, 249,   1,   2, 139]]) tensor([140, 141])
tensor([[237, 238,   1, 134, 142, 136, 124]]) tensor([143, 133, 138])
tensor([[ 1,  2,  3,  4,  5, 69]]) tensor([70])
tensor([[ 94, 187,   2, 102, 200, 201]]) tensor([202])
tensor([[80, 81, 82]]) tensor([83, 84])
tensor([[244, 245, 246,   1,   2, 139]]) tensor([140, 141])
tensor([[ 1,  2,  3,  4,  5, 12]]) tensor([13])
tensor([[244, 245, 246,   1, 134, 135, 136, 124]]) tensor([137, 133, 138])
tensor([[ 80, 173, 177, 178]]) tensor([179, 180, 181])
tensor([[ 94,  95,  96, 213, 214]]) tensor([215])
tensor([[ 96, 241, 243,  80,  85,   3,  86]]) tensor([87, 88, 89])
tensor([[ 80,  81, 171]]) tensor([ 87, 172])
tensor([[ 1,  2,  3,  4,  5, 59]]) tensor([60, 61])
tensor([[  1,   2,   3, 113, 116, 240,  96, 241, 242]]) tensor([115, 116])
tensor([[  1,   2, 122, 123, 124]]) tensor([125, 126])
tensor([[244, 245, 246,   1,   2, 152, 153, 124]]) tensor([154, 155])
tensor([[ 1,  2,  3,  4,  5, 54, 55]]) tensor([56])
tensor([[247,   1, 248, 249,  80,  81, 171]]) tensor([ 87, 172])
tensor([[ 94, 209, 210, 256, 240,  96, 241, 242]]) tensor([212])
tensor([[237, 238,   1,   2,   3, 113, 114]]) tensor([115, 116])
tensor([[ 1,  2,  3,  4,  5, 22]]) tensor([23, 24])
tensor([[ 96, 241, 243,   1,   2, 144, 145]]) tensor([146, 147])
tensor([[ 1,  2,  3,  4,  5, 50]]) tensor([51])
tensor([[252, 241, 253, 254,  94, 203,   2, 207]]) tensor([208])
tensor([[244, 245, 246,   1, 134, 159, 160]]) tensor([161, 162, 163])
tensor([[ 94, 101,   2, 102, 103,   3, 104, 101, 240,  96, 241, 242]]) tensor([106])
tensor([[  1,   2, 127, 123, 124]]) tensor([128, 129])
tensor([[252, 241, 253, 254,   1,   2, 144, 145]]) tensor([146, 147])
tensor([[ 96, 241, 243,  80,  85,   3, 164, 165]]) tensor([166, 167])
tensor([[252, 241, 253, 254,   1,   2, 139]]) tensor([140, 141])
tensor([[ 1,  2,  3,  4,  5, 40]]) tensor([41, 42])
tensor([[237, 238,   1,   2, 127, 123, 124]]) tensor([128, 129])
tensor([[244, 245, 246,  80,  85,   3, 168]]) tensor([169, 170])
tensor([[ 96, 241, 243,   1,   2,   3, 227, 132,   5,  18]]) tensor([228])
tensor([[  1,   2,   3, 113, 114]]) tensor([115, 116])
tensor([[  1,   2, 156]]) tensor([157, 158, 132])
tensor([[ 96, 241, 243,   1,   2,   3, 227, 230, 231,  71,  72]]) tensor([232])
tensor([[247,   1, 248, 249,   1,   2, 122, 123, 124]]) tensor([125, 126])
tensor([[ 96, 241, 243,  94, 182,   2, 102, 103,   3, 183,   5, 184, 185]]) tensor([186])
tensor([[ 1,  2,  3,  4,  5, 67]]) tensor([68])
tensor([[ 80,  85,   3, 164, 260, 240,  96, 241, 242]]) tensor([166, 167])
tensor([[  1,   2, 152, 153, 124]]) tensor([154, 155])
tensor([[ 94, 182,   2, 102, 103,   3, 183,   5, 184, 185]]) tensor([186])
tensor([[252, 241, 253, 254,  80,  81,  82]]) tensor([83, 84])
tensor([[ 80,  85,   3, 250, 240,  96, 241, 242]]) tensor([87, 88, 89])
tensor([[ 94, 187,   2,   3, 113, 192, 193]]) tensor([194, 195])
tensor([[ 96, 241, 243,   1, 134, 142, 136, 124]]) tensor([143, 133, 138])
tensor([[247,   1, 248, 249,  80,  81,  82]]) tensor([83, 84])
tensor([[252, 241, 253, 254,   1,   2, 122, 123, 124]]) tensor([125, 126])
tensor([[  1,   2,   3, 227, 132,   5,  18]]) tensor([228])
tensor([[252, 241, 253, 254,   1, 134, 135, 136, 124]]) tensor([137, 133, 138])
tensor([[252, 241, 253, 254,  80,  85,   3, 164, 165]]) tensor([166, 167])
tensor([[247,   1, 248, 249,  94,  95,  96,  97,  98]]) tensor([ 99, 100])
tensor([[ 80, 117,   3, 118,   5, 119]]) tensor([120, 121])
tensor([[252, 241, 253, 254,  94, 196, 197, 198]]) tensor([199])
tensor([[ 94, 182,   2, 102, 103,   3, 183,   5, 184, 261, 240,  96, 241, 242]]) tensor([186])
tensor([[ 96, 241, 243,   1,   2,   3, 113, 114]]) tensor([115, 116])
tensor([[252, 241, 253, 254,   1,   2, 127, 123, 124]]) tensor([128, 129])
tensor([[252, 241, 253, 254,   1,   2,  90,  91,  92]]) tensor([93])
tensor([[237, 238,  94, 187,   2, 188,   3, 189,   5, 190]]) tensor([191])
tensor([[244, 245, 246,  94, 209, 210, 211]]) tensor([212])
tensor([[ 1,  2,  3,  4,  5, 46]]) tensor([47])
tensor([[247,   1, 248, 249,  94, 222, 223, 220]]) tensor([224])
tensor([[ 96, 241, 243,  94,  95,  96,  97,  98]]) tensor([ 99, 100])
tensor([[237, 238,  94,  95,  96, 213, 214]]) tensor([215])
tensor([[ 1,  2, 90, 91, 92]]) tensor([93])
tensor([[ 94, 222, 223, 251, 240,  96, 241, 242]]) tensor([226])
tensor([[  1, 134, 135, 136, 124]]) tensor([137, 133, 138])
tensor([[ 96, 241, 243,  94, 203,   2, 207]]) tensor([208])
tensor([[252, 241, 253, 254,   1,   2,   3, 233, 187,   5,  50]]) tensor([234, 235, 236])
tensor([[ 1,  2,  3,  4,  5, 36]]) tensor([37])
tensor([[237, 238,  80, 173, 174]]) tensor([175, 176])
tensor([[ 1,  2,  3,  4,  5, 33]]) tensor([34, 35])
tensor([[ 94, 222, 223, 225]]) tensor([226])
tensor([[ 94, 216,   2, 217, 218, 219, 220]]) tensor([221])
tensor([[247,   1, 248, 249,  94, 101,   2, 102, 103,   3, 104, 105]]) tensor([106])
tensor([[1, 2, 3, 4, 5, 6]]) tensor([7])
tensor([[ 96, 241, 243,  80, 173, 174]]) tensor([175, 176])
tensor([[237, 238,  94, 182,   2, 102, 103,   3, 183,   5, 184, 185]]) tensor([186])
tensor([[ 80, 107,   3, 108, 109]]) tensor([110, 111, 112])
tensor([[ 80,  85,   3, 164, 165]]) tensor([166, 167])
tensor([[252, 241, 253, 254,  80, 173, 174]]) tensor([175, 176])
tensor([[252, 241, 253, 254,  94,  95,  96, 213, 214]]) tensor([215])
tensor([[244, 245, 246,  94, 101,   2, 102, 103,   3, 104, 105]]) tensor([106])
tensor([[237, 238,  80,  85,   3, 164, 165]]) tensor([166, 167])
tensor([[244, 245, 246,  94,  95,  96, 213, 214]]) tensor([215])
tensor([[ 1,  2,  3,  4,  5, 25]]) tensor([26])
tensor([[ 1,  2,  3,  4,  5, 27]]) tensor([28])
tensor([[1, 2, 3, 4, 5, 8]]) tensor([9])
tensor([[  1,   2,   3, 227, 230, 231,  71,  72]]) tensor([232])
tensor([[244, 245, 246,   1,   2, 127, 123, 124]]) tensor([128, 129])
tensor([[247,   1, 248, 249,   1, 134, 135, 136, 124]]) tensor([137, 133, 138])
tensor([[247,   1, 248, 249,  80, 173, 177, 178]]) tensor([179, 180, 181])
tensor([[  1,   2, 144, 145]]) tensor([146, 147])
tensor([[ 94, 196, 197, 259, 240,  96, 241, 242]]) tensor([199])
tensor([[ 1,  2,  3,  4,  5, 43, 44]]) tensor([45])
tensor([[247,   1, 248, 249,   1,   2,   3, 113, 114]]) tensor([115, 116])
tensor([[  1,   2, 130, 123, 124]]) tensor([131, 132, 133])
tensor([[94, 95, 96, 97, 98]]) tensor([ 99, 100])
tensor([[ 96, 241, 243,  94, 196, 197, 198]]) tensor([199])
tensor([[247,   1, 248, 249,  94, 187,   2,   3, 113, 192, 193]]) tensor([194, 195])
tensor([[ 94, 209, 210, 211]]) tensor([212])
tensor([[237, 238,  80, 173, 177, 178]]) tensor([179, 180, 181])
tensor([[237, 238,   1,   2,   3, 227, 132,   5,  12]]) tensor([229])
tensor([[247,   1, 248, 249,   1,   2, 144, 145]]) tensor([146, 147])
tensor([[247,   1, 248, 249,   1,   2,  90,  91,  92]]) tensor([93])
tensor([[  1, 134, 148, 136, 124]]) tensor([149, 150, 151])
tensor([[244, 245, 246,  94, 182,   2, 102, 103,   3, 183,   5, 184, 185]]) tensor([186])
tensor([[ 1,  2,  3,  4,  5, 18]]) tensor([19])
tensor([[ 1,  2,  3,  4,  5, 14]]) tensor([15])
tensor([[237, 238,   1,   2,   3, 227, 132,   5,  18]]) tensor([228])
tensor([[237, 238,  94,  95,  96,  97,  98]]) tensor([ 99, 100])
tensor([[ 1,  2,  3,  4,  5, 52]]) tensor([53])
tensor([[ 80, 173, 174]]) tensor([175, 176])
tensor([[  1, 134, 142, 136, 124]]) tensor([143, 133, 138])
tensor([[ 80, 107,   3, 108, 257, 240,  96, 241, 242]]) tensor([110, 111, 112])
tensor([[244, 245, 246,  80, 173, 174]]) tensor([175, 176])
tensor([[247,   1, 248, 249,  94, 222, 223, 225]]) tensor([226])
tensor([[ 1,  2,  3,  4,  5, 20]]) tensor([21])
tensor([[ 96, 241, 243,  80, 173, 177, 178]]) tensor([179, 180, 181])
tensor([[247,   1, 248, 249,  94, 203,   2, 207]]) tensor([208])
tensor([[244, 245, 246,   1,   2, 130, 123, 124]]) tensor([131, 132, 133])
tensor([[247,   1, 248, 249,  80, 107,   3, 108, 109]]) tensor([110, 111, 112])
tensor([[244, 245, 246,  80,  85,   3, 164, 165]]) tensor([166, 167])
tensor([[ 80,  81, 239, 240,  96, 241, 242]]) tensor([ 87, 172])
tensor([[244, 245, 246,   1,   2,  90,  91,  92]]) tensor([93])
tensor([[  1,   2,   3, 227, 132,   5,  12]]) tensor([229])
tensor([[ 80,  85,   3, 168]]) tensor([169, 170])
tensor([[ 1,  2,  3,  4,  5, 78]]) tensor([79])
tensor([[244, 245, 246,  80, 173, 177, 178]]) tensor([179, 180, 181])
tensor([[ 1,  2,  3,  4,  5, 62]]) tensor([63])
tensor([[252, 241, 253, 254,   1,   2,   3, 113, 114]]) tensor([115, 116])
tensor([[ 1,  2,  3,  4,  5, 76]]) tensor([77])
tensor([[247,   1, 248, 249,  80,  85,   3,  86]]) tensor([87, 88, 89])
tensor([[ 1,  2,  3,  4,  5, 16]]) tensor([17])
tensor([[247,   1, 248, 249,  80, 117,   3, 118,   5, 119]]) tensor([120, 121])
tensor([[  1,   2,   3, 233, 187,   5, 258, 240,  96, 241, 242]]) tensor([234, 235, 236])
tensor([[252, 241, 253, 254,  94, 222, 223, 225]]) tensor([226])
tensor([[ 94, 203,   2, 204, 205]]) tensor([206])
tensor([[ 1,  2,  3,  4,  5, 74]]) tensor([75])
tensor([[247,   1, 248, 249,   1, 134, 148, 136, 124]]) tensor([149, 150, 151])
tensor([[  1, 134, 159, 160]]) tensor([161, 162, 163])
tensor([[252, 241, 253, 254,  94, 101,   2, 102, 103,   3, 104, 105]]) tensor([106])

In [58]:
# squeeze

import torch

x = torch.tensor([[[1,2,3]]])

print(x.shape)

y = x.squeeze(0)
print(y.shape)

torch.Size([1, 1, 3])
torch.Size([1, 3])

# RNN Architecture Implementation

In [66]:
import torch.nn as nn
class simpleRNN(nn.Module):
  def __init__(self,vocab_size,embedding_dim=50,hidden_size=64):
    super().__init__()

    self.embedding = nn.Embedding(vocab_size,embedding_dim)
    self.rnn = nn.RNN(embedding_dim,hidden_size,batch_first=True)
    self.fc = nn.Linear(hidden_size,vocab_size)


  def forward(self,question):
    embedded = self.embedding(question)
    _,final = self.rnn(embedded)

    return self.fc(final.squeeze(0))

In [67]:
model = simpleRNN(vocab_size = len(vocab))

#training loop

In [68]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr = 0.0001)
epochs = 50

In [69]:
for epoch in range(epochs):
    total_loss = 0
    for question, answer in dataloader:
        optimizer.zero_grad()
        output = model(question)
        # Fix: take only the first answer token as target → shape (1,)
        target = answer[0][0].unsqueeze(0)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch+1:3d}/{epochs}  |  Loss: {total_loss:.4f}")

Epoch  10/50  |  Loss: 611.0905
Epoch  20/50  |  Loss: 363.1412
Epoch  30/50  |  Loss: 241.4065
Epoch  40/50  |  Loss: 171.0126
Epoch  50/50  |  Loss: 122.2275

#Prediction

In [70]:
vocab.items()

dict_items([('<UNK>', 0), ('what', 1), ('is', 2), ('the', 3), ('capital', 4), ('of', 5), ('france?', 6), ('paris', 7), ('germany?', 8), ('berlin', 9), ('italy?', 10), ('rome', 11), ('spain?', 12), ('madrid', 13), ('japan?', 14), ('tokyo', 15), ('canada?', 16), ('ottawa', 17), ('brazil?', 18), ('brasilia', 19), ('australia?', 20), ('canberra', 21), ('india?', 22), ('new', 23), ('delhi', 24), ('china?', 25), ('beijing', 26), ('russia?', 27), ('moscow', 28), ('united', 29), ('states?', 30), ('washington', 31), ('dc', 32), ('mexico?', 33), ('mexico', 34), ('city', 35), ('egypt?', 36), ('cairo', 37), ('turkey?', 38), ('ankara', 39), ('argentina?', 40), ('buenos', 41), ('aires', 42), ('south', 43), ('korea?', 44), ('seoul', 45), ('indonesia?', 46), ('jakarta', 47), ('pakistan?', 48), ('islamabad', 49), ('bangladesh?', 50), ('dhaka', 51), ('nepal?', 52), ('kathmandu', 53), ('sri', 54), ('lanka?', 55), ('colombo', 56), ('thailand?', 57), ('bangkok', 58), ('malaysia?', 59), ('kuala', 60), ('lumpur', 61), ('vietnam?', 62), ('hanoi', 63), ('uae?', 64), ('abu', 65), ('dhabi', 66), ('iran?', 67), ('tehran', 68), ('iraq?', 69), ('baghdad', 70), ('saudi', 71), ('arabia?', 72), ('riyadh', 73), ('nigeria?', 74), ('abuja', 75), ('kenya?', 76), ('nairobi', 77), ('chile?', 78), ('santiago', 79), ('who', 80), ('discovered', 81), ('gravity?', 82), ('isaac', 83), ('newton', 84), ('invented', 85), ('telephone?', 86), ('alexander', 87), ('graham', 88), ('bell', 89), ('h2o', 90), ('commonly', 91), ('called?', 92), ('water', 93), ('which', 94), ('gas', 95), ('do', 96), ('plants', 97), ('absorb?', 98), ('carbon', 99), ('dioxide', 100), ('planet', 101), ('known', 102), ('as', 103), ('red', 104), ('planet?', 105), ('mars', 106), ('painted', 107), ('mona', 108), ('lisa?', 109), ('leonardo', 110), ('da', 111), ('vinci', 112), ('largest', 113), ('ocean?', 114), ('pacific', 115), ('ocean', 116), ('developed', 117), ('theory', 118), ('relativity?', 119), ('albert', 120), ('einstein', 121), ('ai', 122), ('short', 123), ('for?', 124), ('artificial', 125), ('intelligence', 126), ('ml', 127), ('machine', 128), ('learning', 129), ('nlp', 130), ('natural', 131), ('language', 132), ('processing', 133), ('does', 134), ('cpu', 135), ('stand', 136), ('central', 137), ('unit', 138), ('ram?', 139), ('computer', 140), ('memory', 141), ('gpu', 142), ('graphics', 143), ('a', 144), ('url?', 145), ('web', 146), ('address', 147), ('http', 148), ('hypertext', 149), ('transfer', 150), ('protocol', 151), ('json', 152), ('used', 153), ('data', 154), ('exchange', 155), ('sql?', 156), ('database', 157), ('query', 158), ('api', 159), ('mean?', 160), ('application', 161), ('programming', 162), ('interface', 163), ('light', 164), ('bulb?', 165), ('thomas', 166), ('edison', 167), ('airplane?', 168), ('wright', 169), ('brothers', 170), ('penicillin?', 171), ('fleming', 172), ('wrote', 173), ('hamlet?', 174), ('william', 175), ('shakespeare', 176), ('harry', 177), ('potter?', 178), ('j', 179), ('k', 180), ('rowling', 181), ('country', 182), ('land', 183), ('rising', 184), ('sun?', 185), ('japan', 186), ('animal', 187), ('called', 188), ('king', 189), ('jungle?', 190), ('lion', 191), ('on', 192), ('earth?', 193), ('blue', 194), ('whale', 195), ('bird', 196), ('cannot', 197), ('fly?', 198), ('ostrich', 199), ('for', 200), ('loyalty?', 201), ('dog', 202), ('fruit', 203), ('typically', 204), ('red?', 205), ('apple', 206), ('yellow?', 207), ('banana', 208), ('organ', 209), ('pumps', 210), ('blood?', 211), ('heart', 212), ('humans', 213), ('breathe?', 214), ('oxygen', 215), ('metal', 216), ('liquid', 217), ('at', 218), ('room', 219), ('temperature?', 220), ('mercury', 221), ('instrument', 222), ('measures', 223), ('thermometer', 224), ('pressure?', 225), ('barometer', 226), ('main', 227), ('portuguese', 228), ('spanish', 229), ('religion', 230), ('in', 231), ('islam', 232), ('national', 233), ('royal', 234), ('bengal', 235), ('tiger', 236), ('quick', 237), ('question:', 238), ('penicillin', 239), ('—', 240), ('you', 241), ('know?', 242), ('know,', 243), ('i', 244), ('was', 245), ('wondering,', 246), ('hey,', 247), ('about', 248), ('this:', 249), ('telephone', 250), ('pressure', 251), ('can', 252), ('tell', 253), ('me,', 254), ('earth', 255), ('blood', 256), ('lisa', 257), ('bangladesh', 258), ('fly', 259), ('bulb', 260), ('sun', 261)])

In [71]:
# index to word
idx_to_word = {idx : word for word,idx in vocab.items() }
idx_to_word

{0: '<UNK>',
 1: 'what',
 2: 'is',
 3: 'the',
 4: 'capital',
 5: 'of',
 6: 'france?',
 7: 'paris',
 8: 'germany?',
 9: 'berlin',
 10: 'italy?',
 11: 'rome',
 12: 'spain?',
 13: 'madrid',
 14: 'japan?',
 15: 'tokyo',
 16: 'canada?',
 17: 'ottawa',
 18: 'brazil?',
 19: 'brasilia',
 20: 'australia?',
 21: 'canberra',
 22: 'india?',
 23: 'new',
 24: 'delhi',
 25: 'china?',
 26: 'beijing',
 27: 'russia?',
 28: 'moscow',
 29: 'united',
 30: 'states?',
 31: 'washington',
 32: 'dc',
 33: 'mexico?',
 34: 'mexico',
 35: 'city',
 36: 'egypt?',
 37: 'cairo',
 38: 'turkey?',
 39: 'ankara',
 40: 'argentina?',
 41: 'buenos',
 42: 'aires',
 43: 'south',
 44: 'korea?',
 45: 'seoul',
 46: 'indonesia?',
 47: 'jakarta',
 48: 'pakistan?',
 49: 'islamabad',
 50: 'bangladesh?',
 51: 'dhaka',
 52: 'nepal?',
 53: 'kathmandu',
 54: 'sri',
 55: 'lanka?',
 56: 'colombo',
 57: 'thailand?',
 58: 'bangkok',
 59: 'malaysia?',
 60: 'kuala',
 61: 'lumpur',
 62: 'vietnam?',
 63: 'hanoi',
 64: 'uae?',
 65: 'abu',
 66: 'dhabi',
 67: 'iran?',
 68: 'tehran',
 69: 'iraq?',
 70: 'baghdad',
 71: 'saudi',
 72: 'arabia?',
 73: 'riyadh',
 74: 'nigeria?',
 75: 'abuja',
 76: 'kenya?',
 77: 'nairobi',
 78: 'chile?',
 79: 'santiago',
 80: 'who',
 81: 'discovered',
 82: 'gravity?',
 83: 'isaac',
 84: 'newton',
 85: 'invented',
 86: 'telephone?',
 87: 'alexander',
 88: 'graham',
 89: 'bell',
 90: 'h2o',
 91: 'commonly',
 92: 'called?',
 93: 'water',
 94: 'which',
 95: 'gas',
 96: 'do',
 97: 'plants',
 98: 'absorb?',
 99: 'carbon',
 100: 'dioxide',
 101: 'planet',
 102: 'known',
 103: 'as',
 104: 'red',
 105: 'planet?',
 106: 'mars',
 107: 'painted',
 108: 'mona',
 109: 'lisa?',
 110: 'leonardo',
 111: 'da',
 112: 'vinci',
 113: 'largest',
 114: 'ocean?',
 115: 'pacific',
 116: 'ocean',
 117: 'developed',
 118: 'theory',
 119: 'relativity?',
 120: 'albert',
 121: 'einstein',
 122: 'ai',
 123: 'short',
 124: 'for?',
 125: 'artificial',
 126: 'intelligence',
 127: 'ml',
 128: 'machine',
 129: 'learning',
 130: 'nlp',
 131: 'natural',
 132: 'language',
 133: 'processing',
 134: 'does',
 135: 'cpu',
 136: 'stand',
 137: 'central',
 138: 'unit',
 139: 'ram?',
 140: 'computer',
 141: 'memory',
 142: 'gpu',
 143: 'graphics',
 144: 'a',
 145: 'url?',
 146: 'web',
 147: 'address',
 148: 'http',
 149: 'hypertext',
 150: 'transfer',
 151: 'protocol',
 152: 'json',
 153: 'used',
 154: 'data',
 155: 'exchange',
 156: 'sql?',
 157: 'database',
 158: 'query',
 159: 'api',
 160: 'mean?',
 161: 'application',
 162: 'programming',
 163: 'interface',
 164: 'light',
 165: 'bulb?',
 166: 'thomas',
 167: 'edison',
 168: 'airplane?',
 169: 'wright',
 170: 'brothers',
 171: 'penicillin?',
 172: 'fleming',
 173: 'wrote',
 174: 'hamlet?',
 175: 'william',
 176: 'shakespeare',
 177: 'harry',
 178: 'potter?',
 179: 'j',
 180: 'k',
 181: 'rowling',
 182: 'country',
 183: 'land',
 184: 'rising',
 185: 'sun?',
 186: 'japan',
 187: 'animal',
 188: 'called',
 189: 'king',
 190: 'jungle?',
 191: 'lion',
 192: 'on',
 193: 'earth?',
 194: 'blue',
 195: 'whale',
 196: 'bird',
 197: 'cannot',
 198: 'fly?',
 199: 'ostrich',
 200: 'for',
 201: 'loyalty?',
 202: 'dog',
 203: 'fruit',
 204: 'typically',
 205: 'red?',
 206: 'apple',
 207: 'yellow?',
 208: 'banana',
 209: 'organ',
 210: 'pumps',
 211: 'blood?',
 212: 'heart',
 213: 'humans',
 214: 'breathe?',
 215: 'oxygen',
 216: 'metal',
 217: 'liquid',
 218: 'at',
 219: 'room',
 220: 'temperature?',
 221: 'mercury',
 222: 'instrument',
 223: 'measures',
 224: 'thermometer',
 225: 'pressure?',
 226: 'barometer',
 227: 'main',
 228: 'portuguese',
 229: 'spanish',
 230: 'religion',
 231: 'in',
 232: 'islam',
 233: 'national',
 234: 'royal',
 235: 'bengal',
 236: 'tiger',
 237: 'quick',
 238: 'question:',
 239: 'penicillin',
 240: '—',
 241: 'you',
 242: 'know?',
 243: 'know,',
 244: 'i',
 245: 'was',
 246: 'wondering,',
 247: 'hey,',
 248: 'about',
 249: 'this:',
 250: 'telephone',
 251: 'pressure',
 252: 'can',
 253: 'tell',
 254: 'me,',
 255: 'earth',
 256: 'blood',
 257: 'lisa',
 258: 'bangladesh',
 259: 'fly',
 260: 'bulb',
 261: 'sun'}

In [72]:

def predict(question_text,model,vocab,idx_to_word):
  model.eval()

  with torch.no_grad():
    indices = text_to_indices(question_text,vocab)

    if not indices:
      return ""

    x = torch.tensor(indices).unsqueeze(0)  #batch size, sequence legth

    pred = torch.argmax(model(x),dim=1).item()


  return idx_to_word.get(pred,"")

In [73]:

# Test
tests = [
    "What is the capital of France?",
    "What is H2O commonly called?",
    "Which planet is known as the red planet?",
    "Which bird cannot fly?",
    "What is the capital of Japan ?",

]
for q in tests:
    print(f"{q:45} → {predict(q, model, vocab, idx_to_word)}")

What is the capital of France?                → paris
What is H2O commonly called?                  → water
Which planet is known as the red planet?      → mars
Which bird cannot fly?                        → ostrich
What is the capital of Japan ?                → william